version: '3.9'

services:
  app:
    container_name: AMTracker
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
      - ./docker-config/php/php.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    
  db:
    image: postgres:16
    container_name: AMTracker_db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME} 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
 
volumes:
  postgres_data: {} 
  